// Auto-generated by scrape-fish-data.py -- do not hand-edit.
// To refresh: `python scrape-fish-data.py > fish-catalog.snippet.js`
//
// This data is derived from the Old School RuneScape Wiki and is licensed
// under CC BY-NC-SA 3.0 (https://creativecommons.org/licenses/by-nc-sa/3.0/),
// NOT the repository's MIT code license. It uses material from the per-fish
// articles and {{Skilling success chart}} template on the OSRS Wiki
// (https://oldschool.runescape.wiki). See LICENSE-DATA.md for details.
window.TRAINING_DATA_FISH_CATALOG = [
  {
    id: "shrimp", name: "Shrimp", color: "#b18065",
    fishLevel: 1, fishXp: 10,
    cookLevel: 1, cookXp: 30,
    gauntletsAffected: false,
    catch: {"default": {"low": 48, "high": 256, "req": 1}},
    cook: {"fire": {"low": 128, "high": 512, "req": 1}, "range": {"low": 128, "high": 512, "req": 1}, "lumbridge": {"low": 138, "high": 532, "req": 1}, "hosidius-5": {"low": 140, "high": 524, "req": 1}, "hosidius-10": {"low": 153, "high": 537, "req": 84}}
  },
  {
    id: "anchovy", name: "Anchovy", color: "#6e6e8b",
    fishLevel: 15, fishXp: 40,
    cookLevel: 1, cookXp: 30,
    gauntletsAffected: false,
    catch: {"default": {"low": 24, "high": 128, "req": 15}},
    cook: {"fire": {"low": 128, "high": 512, "req": 1}, "range": {"low": 128, "high": 512, "req": 1}, "lumbridge": {"low": 138, "high": 532, "req": 1}, "hosidius-5": {"low": 140, "high": 524, "req": 1}, "hosidius-10": {"low": 153, "high": 537, "req": 84}}
  },
  {
    id: "sardine", name: "Sardine", color: "#c19a6b",
    fishLevel: 5, fishXp: 20,
    cookLevel: 1, cookXp: 40,
    gauntletsAffected: false,
    catch: {"default": {"low": 32, "high": 192, "req": 5}},
    cook: {"fire": {"low": 118, "high": 492, "req": 1}, "range": {"low": 118, "high": 492, "req": 1}, "lumbridge": {"low": 128, "high": 512, "req": 1}, "hosidius-5": {"low": 130, "high": 504, "req": 1}, "hosidius-10": {"low": 143, "high": 517, "req": 79}}
  },
  {
    id: "herring", name: "Herring", color: "#9aa6b8",
    fishLevel: 10, fishXp: 30,
    cookLevel: 5, cookXp: 50,
    gauntletsAffected: false,
    catch: {"default": {"low": 24, "high": 128, "req": 10}},
    cook: {"fire": {"low": 108, "high": 472, "req": 5}, "range": {"low": 108, "high": 472, "req": 5}, "lumbridge": {"low": 118, "high": 492, "req": 5}, "hosidius-5": {"low": 120, "high": 484, "req": 5}, "hosidius-10": {"low": 133, "high": 497, "req": 79}}
  },
  {
    id: "mackerel", name: "Mackerel", color: "#3a7ca5",
    fishLevel: 16, fishXp: 20,
    cookLevel: 10, cookXp: 60,
    gauntletsAffected: false,
    catch: {"default": {"low": 5, "high": 65, "req": 16}},
    cook: {"fire": {"low": 98, "high": 452, "req": 10}, "range": {"low": 98, "high": 452, "req": 10}, "lumbridge": {"low": 108, "high": 472, "req": 10}, "hosidius-5": {"low": 110, "high": 464, "req": 10}, "hosidius-10": {"low": 123, "high": 477, "req": 79}}
  },
  {
    id: "cod", name: "Cod", color: "#6a8caf",
    fishLevel: 23, fishXp: 45,
    cookLevel: 18, cookXp: 75,
    gauntletsAffected: false,
    catch: {"default": {"low": 4, "high": 55, "req": 23}},
    cook: {"fire": {"low": 83, "high": 422, "req": 18}, "range": {"low": 88, "high": 432, "req": 18}, "lumbridge": {"low": 93, "high": 442, "req": 18}, "hosidius-5": {"low": 100, "high": 444, "req": 18}, "hosidius-10": {"low": 113, "high": 457, "req": 79}}
  },
  {
    id: "bass", name: "Bass", color: "#86936b",
    fishLevel: 46, fishXp: 100,
    cookLevel: 43, cookXp: 130,
    gauntletsAffected: false,
    catch: {"default": {"low": 3, "high": 40, "req": 46}},
    cook: {"fire": {"low": 33, "high": 312, "req": 43}, "range": {"low": 33, "high": 312, "req": 43}, "hosidius-5": {"low": 45, "high": 324, "req": 43}, "hosidius-10": {"low": 58, "high": 337, "req": 79}}
  },
  {
    id: "trout", name: "Trout", color: "#d28a5e",
    fishLevel: 20, fishXp: 50,
    cookLevel: 15, cookXp: 70,
    gauntletsAffected: false,
    catch: {"default": {"low": 32, "high": 192, "req": 20}},
    cook: {"fire": {"low": 88, "high": 432, "req": 15}, "range": {"low": 88, "high": 432, "req": 15}, "lumbridge": {"low": 98, "high": 452, "req": 15}, "hosidius-5": {"low": 100, "high": 444, "req": 15}, "hosidius-10": {"low": 113, "high": 457, "req": 79}}
  },
  {
    id: "salmon", name: "Salmon", color: "#e07b5c",
    fishLevel: 30, fishXp: 70,
    cookLevel: 25, cookXp: 90,
    gauntletsAffected: false,
    catch: {"default": {"low": 16, "high": 96, "req": 30}},
    cook: {"fire": {"low": 68, "high": 392, "req": 25}, "range": {"low": 68, "high": 392, "req": 25}, "lumbridge": {"low": 78, "high": 402, "req": 25}, "hosidius-5": {"low": 80, "high": 404, "req": 25}, "hosidius-10": {"low": 93, "high": 417, "req": 79}}
  },
  {
    id: "pike", name: "Pike", color: "#7c8556",
    fishLevel: 25, fishXp: 60,
    cookLevel: 20, cookXp: 80,
    gauntletsAffected: false,
    catch: {"default": {"low": 16, "high": 96, "req": 25}},
    cook: {"fire": {"low": 78, "high": 412, "req": 20}, "range": {"low": 78, "high": 412, "req": 20}, "lumbridge": {"low": 88, "high": 432, "req": 20}, "hosidius-5": {"low": 90, "high": 424, "req": 20}, "hosidius-10": {"low": 103, "high": 437, "req": 79}}
  },
  {
    id: "tuna", name: "Tuna", color: "#4e6e8e",
    fishLevel: 35, fishXp: 80,
    cookLevel: 30, cookXp: 100,
    gauntletsAffected: false,
    catch: {"harpoon": {"low": 8, "high": 64, "req": 35}, "dragon-harpoon": {"low": 9, "high": 76, "req": 35}, "crystal-harpoon": {"low": 10, "high": 86, "req": 35}},
    cook: {"fire": {"low": 58, "high": 372, "req": 30}, "range": {"low": 58, "high": 372, "req": 30}, "hosidius-5": {"low": 70, "high": 384, "req": 30}, "hosidius-10": {"low": 83, "high": 397, "req": 79}}
  },
  {
    id: "lobster", name: "Lobster", color: "#c8553d",
    fishLevel: 40, fishXp: 90,
    cookLevel: 40, cookXp: 120,
    gauntletsAffected: true,
    catch: {"default": {"low": 6, "high": 95, "req": 40}},
    cook: {"fire": {"low": 38, "high": 332, "req": 40}, "range": {"low": 38, "high": 332, "req": 40}, "hosidius-5": {"low": 50, "high": 344, "req": 40}, "hosidius-10": {"low": 63, "high": 357, "req": 79}},
    cookGauntlets: {"fire": {"low": 55, "high": 368, "req": 40}, "range": {"low": 55, "high": 368, "req": 40}, "hosidius-5": {"low": 67, "high": 380, "req": 40}, "hosidius-10": {"low": 80, "high": 393, "req": 79}}
  },
  {
    id: "swordfish", name: "Swordfish", color: "#5a8fa8",
    fishLevel: 50, fishXp: 100,
    cookLevel: 45, cookXp: 140,
    gauntletsAffected: true,
    catch: {"harpoon": {"low": 4, "high": 48, "req": 50}, "dragon-harpoon": {"low": 4, "high": 57, "req": 50}, "crystal-harpoon": {"low": 5, "high": 64, "req": 50}},
    cook: {"fire": {"low": 18, "high": 292, "req": 45}, "range": {"low": 30, "high": 310, "req": 45}, "hosidius-5": {"low": 42, "high": 322, "req": 45}, "hosidius-10": {"low": 55, "high": 335, "req": 79}},
    cookGauntlets: {"fire": {"low": 30, "high": 310, "req": 45}}
  },
  {
    id: "monkfish", name: "Monkfish", color: "#86a07c",
    fishLevel: 62, fishXp: 120,
    cookLevel: 62, cookXp: 150,
    gauntletsAffected: true,
    catch: {"default": {"low": 48, "high": 90, "req": 62}},
    cook: {"fire": {"low": 11, "high": 275, "req": 62}, "range": {"low": 13, "high": 280, "req": 62}, "hosidius-5": {"low": 25, "high": 292, "req": 62}, "hosidius-10": {"low": 38, "high": 305, "req": 79}},
    cookGauntlets: {"fire": {"low": 24, "high": 290, "req": 62}, "range": {"low": 24, "high": 290, "req": 62}, "hosidius-5": {"low": 36, "high": 302, "req": 62}, "hosidius-10": {"low": 49, "high": 315, "req": 79}}
  },
  {
    id: "shark", name: "Shark", color: "#4d6b87",
    fishLevel: 76, fishXp: 110,
    cookLevel: 80, cookXp: 210,
    gauntletsAffected: true,
    catch: {"harpoon": {"low": 3, "high": 40, "req": 76}, "dragon-harpoon": {"low": 3, "high": 48, "req": 76}, "crystal-harpoon": {"low": 4, "high": 54, "req": 76}},
    cook: {"fire": {"low": 1, "high": 202, "req": 80}, "range": {"low": 1, "high": 232, "req": 80}, "hosidius-5": {"low": 13, "high": 244, "req": 80}, "hosidius-10": {"low": 26, "high": 257, "req": 80}},
    cookGauntlets: {"fire": {"low": 15, "high": 270, "req": 80}, "range": {"low": 15, "high": 270, "req": 80}, "hosidius-5": {"low": 27, "high": 282, "req": 80}, "hosidius-10": {"low": 40, "high": 295, "req": 80}}
  },
  {
    id: "anglerfish", name: "Anglerfish", color: "#9b6b8a",
    fishLevel: 82, fishXp: 120,
    cookLevel: 84, cookXp: 230,
    gauntletsAffected: true,
    catch: {"default": {"low": 3, "high": 36, "req": 82}},
    cook: {"fire": {"low": 1, "high": 200, "req": 84}, "range": {"low": 1, "high": 220, "req": 84}, "hosidius-5": {"low": 13, "high": 232, "req": 84}, "hosidius-10": {"low": 26, "high": 245, "req": 84}},
    cookGauntlets: {"fire": {"low": 12, "high": 260, "req": 84}, "range": {"low": 12, "high": 260, "req": 84}, "hosidius-5": {"low": 24, "high": 272, "req": 84}, "hosidius-10": {"low": 37, "high": 285, "req": 84}}
  },
  {
    id: "darkCrab", name: "Dark crab", color: "#444",
    fishLevel: 85, fishXp: 130,
    cookLevel: 90, cookXp: 215,
    gauntletsAffected: false,
    catch: {"default": {"low": 3, "high": 40, "req": 85}},
    cook: {"fire": {"low": 10, "high": 222, "req": 90}, "range": {"low": 10, "high": 222, "req": 90}, "hosidius-5": {"low": 22, "high": 234, "req": 90}, "hosidius-10": {"low": 35, "high": 247, "req": 90}}
  },
];
