// GENERATED by scrape-mining-data.py — do not hand-edit.
// OSRS mining rock success curves from the OSRS Wiki {{Skilling success chart}} templates,
// reused under CC BY-NC-SA 3.0 (https://creativecommons.org/licenses/by-nc-sa/3.0/).
window.TRAINING_DATA_MINING_CATALOG = [
  {
    "id": "clay",
    "name": "Clay",
    "gatherLevel": 1,
    "gatherXp": 5,
    "low": 128.0,
    "high": 400.0,
    "respawnSec": 1.2,
    "color": "#b08d57"
  },
  {
    "id": "copper",
    "name": "Copper ore",
    "gatherLevel": 1,
    "gatherXp": 17.5,
    "low": 100.0,
    "high": 350.0,
    "respawnSec": 2.4,
    "color": "#b87333"
  },
  {
    "id": "tin",
    "name": "Tin ore",
    "gatherLevel": 1,
    "gatherXp": 17.5,
    "low": 100.0,
    "high": 350.0,
    "respawnSec": 2.4,
    "color": "#cfcfcf"
  },
  {
    "id": "iron",
    "name": "Iron ore",
    "gatherLevel": 15,
    "gatherXp": 35,
    "low": 96.0,
    "high": 350.0,
    "respawnSec": 5.4,
    "color": "#8a5a44"
  },
  {
    "id": "silver",
    "name": "Silver ore",
    "gatherLevel": 20,
    "gatherXp": 40,
    "low": 25.0,
    "high": 200.0,
    "respawnSec": 60,
    "color": "#c0c0c8"
  },
  {
    "id": "coal",
    "name": "Coal",
    "gatherLevel": 30,
    "gatherXp": 50,
    "low": 16.0,
    "high": 100.0,
    "respawnSec": 30,
    "color": "#3a3a3a"
  },
  {
    "id": "gold",
    "name": "Gold ore",
    "gatherLevel": 40,
    "gatherXp": 65,
    "low": 7.0,
    "high": 75.0,
    "respawnSec": 60,
    "color": "#d4af37"
  },
  {
    "id": "mithril",
    "name": "Mithril ore",
    "gatherLevel": 55,
    "gatherXp": 80,
    "low": 4.0,
    "high": 50.0,
    "respawnSec": 120,
    "color": "#4f6bb0"
  },
  {
    "id": "adamantite",
    "name": "Adamantite ore",
    "gatherLevel": 70,
    "gatherXp": 95,
    "low": 2.0,
    "high": 25.0,
    "respawnSec": 240,
    "color": "#3f7d5a"
  },
  {
    "id": "runite",
    "name": "Runite ore",
    "gatherLevel": 85,
    "gatherXp": 125,
    "low": 1.0,
    "high": 18.0,
    "respawnSec": 720,
    "color": "#3fa7a0"
  }
];
