#!/usr/bin/env python3
"""Scrape OSRS mining success curves into mining-catalog.snippet.js.

For each rock, fetch its wiki page and parse the {{Skilling success chart}}
template's low1/high1/req1 params (the same template/format the fish pages use).
gatherXp/respawnSec/colour are hand-mapped here (XP from Module:Skill calc/Mining,
respawn from each rock infobox) since they are not in the success-chart template.

Run:  python scrape-mining-data.py > mining-catalog.snippet.js
"""
import re, sys, json, httpx

UA = {"User-Agent": "OSRS-tool mining scraper (https://github.com/Aiadan/OSRS-tool)"}
BASE = "https://oldschool.runescape.wiki"

# id -> (wiki page, display name, gatherXp, respawnSec, colour)
ROCKS = [
    ("clay",       "Clay rocks",       "Clay",       5,    1.2, "#b08d57"),
    ("copper",     "Copper rocks",     "Copper ore", 17.5, 2.4, "#b87333"),
    ("tin",        "Tin rocks",        "Tin ore",    17.5, 2.4, "#cfcfcf"),
    ("iron",       "Iron rocks",       "Iron ore",   35,   5.4, "#8a5a44"),
    ("silver",     "Silver rocks",     "Silver ore", 40,   60,  "#c0c0c8"),
    ("coal",       "Coal rocks",       "Coal",       50,   30,  "#3a3a3a"),
    ("gold",       "Gold rocks",       "Gold ore",   65,   60,  "#d4af37"),
    ("mithril",    "Mithril rocks",    "Mithril ore",80,   120, "#4f6bb0"),
    ("adamantite", "Adamantite rocks", "Adamantite ore", 95, 240, "#3f7d5a"),
    ("runite",     "Runite rocks",     "Runite ore", 125,  720, "#3fa7a0"),
]

def chart_params(wikitext):
    m = re.search(r"\{\{Skilling success chart(.*?)\}\}", wikitext, re.I | re.S)
    if not m:
        return None
    body = m.group(1)
    def g(name):
        mm = re.search(name + r"\s*=\s*([\d.]+)", body)
        return float(mm.group(1)) if mm else None
    return g("low1"), g("high1"), g("req1")

def main():
    sys.stdout.reconfigure(encoding="utf-8")
    out = []
    for rid, page, name, xp, respawn, color in ROCKS:
        r = httpx.get(f"{BASE}/w/{page}", params={"action": "raw"},
                      headers=UA, timeout=30, follow_redirects=True)
        params = chart_params(r.text)
        if not params or None in params:
            sys.stderr.write(f"WARN: no success chart for {rid} ({page})\n")
            continue
        low, high, req = params
        out.append({"id": rid, "name": name, "gatherLevel": int(req),
                    "gatherXp": xp, "low": low, "high": high,
                    "respawnSec": respawn, "color": color})
        sys.stderr.write(f"{rid:11} low={low} high={high} req={int(req)}\n")

    print("// GENERATED by scrape-mining-data.py — do not hand-edit.")
    print("// OSRS mining rock success curves from the OSRS Wiki "
          "{{Skilling success chart}} templates,")
    print("// reused under CC BY-NC-SA 3.0 (https://creativecommons.org/licenses/by-nc-sa/3.0/).")
    print("window.TRAINING_DATA_MINING_CATALOG = " + json.dumps(out, indent=2) + ";")

if __name__ == "__main__":
    main()
