// Auto-generated by scrape-thieving-data.py -- do not hand-edit.
// To refresh: `python scrape-thieving-data.py > thieving-catalog.snippet.js`
//
// This data is derived from the Old School RuneScape Wiki and is licensed
// under CC BY-NC-SA 3.0 (https://creativecommons.org/licenses/by-nc-sa/3.0/),
// NOT the repository's MIT code license. It uses material from the
// pickpocket-target articles and {{Skilling success chart}} template on the
// OSRS Wiki (https://oldschool.runescape.wiki). See LICENSE-DATA.md for details.
window.TRAINING_DATA_THIEVING = {
  pickpocket: [
    { id: "man", name: "Man / Woman", color: "#9aa6b8", level: 1, xp: 8, success: { low: 180, high: 240, req: 1 } },
    { id: "farmer", name: "Farmer", color: "#8f9d4f", level: 10, xp: 14.5, success: { low: 150, high: 240, req: 7 } },
    { id: "hamMember", name: "H.A.M. member", color: "#7a6a4f", level: 15, xp: 22.2, success: { low: 135, high: 239, req: 15 } },
    { id: "warrior", name: "Warrior", color: "#b06f3c", level: 25, xp: 26, success: { low: 100, high: 240, req: 25 } },
    { id: "rogue", name: "Rogue", color: "#6e6e8b", level: 32, xp: 36.5, success: { low: 75, high: 240, req: 32 } },
    { id: "masterFarmer", name: "Master Farmer", color: "#c8a06b", level: 38, xp: 43, success: { low: 90, high: 240, req: 38 } },
    { id: "guard", name: "Guard", color: "#5a8fa8", level: 40, xp: 46.8, success: { low: 50, high: 240, req: 40 } },
    { id: "wealthy", name: "Wealthy citizen", color: "#c8553d", level: 50, xp: 96, success: { low: 35, high: 200, req: 50 } },
    { id: "desertBandit", name: "Desert Bandit", color: "#d6a754", level: 53, xp: 79.4, success: { low: 50, high: 240, req: 53 } },
    { id: "knight", name: "Knight of Ardougne", color: "#5a8fa8", level: 55, xp: 84.3, success: { low: 50, high: 240, req: 55 } },
    { id: "watchman", name: "Watchman", color: "#7b6cd9", level: 65, xp: 137.5, success: { low: 15, high: 160, req: 65 } },
    { id: "menaphiteThug", name: "Menaphite Thug", color: "#a55a2d", level: 65, xp: 137.5, success: { low: 50, high: 160, req: 65 } },
    { id: "paladin", name: "Paladin", color: "#d28a5e", level: 70, xp: 131.8, success: { low: 35, high: 160, req: 70 } },
    { id: "gnome", name: "Gnome", color: "#7eb47e", level: 75, xp: 133.3, success: { low: 33, high: 140, req: 75 } },
    { id: "hero", name: "Hero", color: "#c97070", level: 80, xp: 163.3, success: { low: 39, high: 160, req: 80 } },
    { id: "vyre", name: "Vyre", color: "#76273a", level: 82, xp: 306.9, success: { low: 8, high: 128, req: 82 } },
    { id: "elf", name: "Elf", color: "#9b6b8a", level: 85, xp: 353.3, success: { low: 6, high: 100, req: 85 } },
  ],
  stalls: [
    { id: "veg", name: "Vegetable stall", color: "#8f9d4f", level: 2, xp: 10, respawn: 1.2 },
    { id: "bakery", name: "Bakery stall", color: "#c8a06b", level: 5, xp: 16, respawn: 2.4 },
    { id: "tea", name: "Tea stall", color: "#a3804f", level: 5, xp: 16, respawn: 2.4 },
    { id: "crafting", name: "Crafting stall", color: "#7a8056", level: 5, xp: 20, respawn: 4.8 },
    { id: "silk", name: "Silk stall", color: "#9b6b8a", level: 20, xp: 24, respawn: 4.8 },
    { id: "wine", name: "Wine stall", color: "#76273a", level: 22, xp: 27, respawn: 4.8 },
    { id: "fruit", name: "Fruit stall", color: "#d68754", level: 25, xp: 28.5, respawn: 2.4 },
    { id: "seed", name: "Seed stall", color: "#8f9d4f", level: 27, xp: 10, respawn: 2.4 },
    { id: "fur", name: "Fur stall", color: "#a55a2d", level: 35, xp: 45, respawn: 7.2 },
    { id: "fish", name: "Fish stall", color: "#5a8fa8", level: 42, xp: 42, respawn: 7.2 },
    { id: "crossbow", name: "Crossbow stall", color: "#6e6e6e", level: 49, xp: 52, respawn: 4.8 },
    { id: "silver", name: "Silver stall", color: "#c0c0c0", level: 50, xp: 205, respawn: 19.2 },
    { id: "spice", name: "Spice stall", color: "#d6a754", level: 65, xp: 92, respawn: 6 },
    { id: "magic", name: "Magic stall", color: "#7b6cd9", level: 65, xp: 90, respawn: 7.2 },
    { id: "scimitar", name: "Scimitar stall", color: "#9aa6b8", level: 65, xp: 210, respawn: 19.2 },
    { id: "gem", name: "Gem stall", color: "#c8553d", level: 75, xp: 408, respawn: 60 },
    { id: "oreTzhaar", name: "Ore stall (Mor Ul Rek)", color: "#a02020", level: 82, xp: 350, respawn: 30 },
    { id: "cannonball", name: "Cannonball stall", color: "#444", level: 87, xp: 223, respawn: 2.4 },
  ]
};
